// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servientrega.Api.Data;

#nullable disable

namespace Servientrega.Api.Migrations
{
    [DbContext(typeof(ServientregaDbContext))]
    [Migration("20260702032943_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Servientrega.Api.Models.Envio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("HoraEntregaEstimada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("HoraEntregaReal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("HoraSalida")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId")
                        .IsUnique();

                    b.ToTable("Envios");
                });

            modelBuilder.Entity("Servientrega.Api.Models.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UbicacionDestino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UbicacionOrigen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("Servientrega.Api.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Servientrega.Api.Models.Valoracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EnvioId")
                        .HasColumnType("int");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId")
                        .IsUnique();

                    b.ToTable("Valoraciones");
                });

            modelBuilder.Entity("Servientrega.Api.Models.Envio", b =>
                {
                    b.HasOne("Servientrega.Api.Models.Orden", "Orden")
                        .WithOne("Envio")
                        .HasForeignKey("Servientrega.Api.Models.Envio", "OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("Servientrega.Api.Models.Producto", b =>
                {
                    b.HasOne("Servientrega.Api.Models.Orden", null)
                        .WithMany("Productos")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Servientrega.Api.Models.Valoracion", b =>
                {
                    b.HasOne("Servientrega.Api.Models.Envio", "Envio")
                        .WithOne("Valoracion")
                        .HasForeignKey("Servientrega.Api.Models.Valoracion", "EnvioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Envio");
                });

            modelBuilder.Entity("Servientrega.Api.Models.Envio", b =>
                {
                    b.Navigation("Valoracion");
                });

            modelBuilder.Entity("Servientrega.Api.Models.Orden", b =>
                {
                    b.Navigation("Envio");

                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
