// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servientrega.Api.Data;

#nullable disable

namespace Servientrega.Api.Migrations
{
    [DbContext(typeof(ServientregaDbContext))]
    partial class ServientregaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Servientrega.Api.Models.Envio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("HoraEntregaEstimada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("HoraEntregaReal")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("HoraSalida")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId")
                        .IsUnique();

                    b.ToTable("Envios");
                });

            modelBuilder.Entity("Servientrega.Api.Models.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DireccionEntrega")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonoContacto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UbicacionDestino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UbicacionOrigen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("Servientrega.Api.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Servientrega.Api.Models.ProductoCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Catalogo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "RTX 4060, 16GB RAM, 1TB SSD",
                            ImagenUrl = "ri-macbook-line",
                            Nombre = "Laptop Gaming ASUS",
                            Precio = 1200.00m
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Titanium, 256GB, Color Natural",
                            ImagenUrl = "ri-smartphone-line",
                            Nombre = "iPhone 15 Pro",
                            Precio = 999.00m
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Cancelación de ruido activa, Inalámbricos",
                            ImagenUrl = "ri-headphone-line",
                            Nombre = "Audífonos Sony WH-1000XM5",
                            Precio = 349.00m
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Consola híbrida de 64GB",
                            ImagenUrl = "ri-gamepad-line",
                            Nombre = "Nintendo Switch OLED",
                            Precio = 349.99m
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "34 pulgadas, 144Hz, IPS",
                            ImagenUrl = "ri-computer-line",
                            Nombre = "Monitor LG UltraWide",
                            Precio = 450.00m
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Cámara Mirrorless Full-Frame 33MP",
                            ImagenUrl = "ri-camera-line",
                            Nombre = "Cámara Sony Alpha a7 IV",
                            Precio = 2499.00m
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Mecánico inalámbrico, RGB",
                            ImagenUrl = "ri-keyboard-line",
                            Nombre = "Teclado Keychron K8 Pro",
                            Precio = 110.00m
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Ergonómico, sensor láser 8K DPI",
                            ImagenUrl = "ri-mouse-line",
                            Nombre = "Mouse Logitech MX Master 3S",
                            Precio = 99.99m
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "45mm, GPS, Midnight Aluminum",
                            ImagenUrl = "ri-smart-watch-line",
                            Nombre = "Apple Watch Series 9",
                            Precio = 399.00m
                        });
                });

            modelBuilder.Entity("Servientrega.Api.Models.Valoracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EnvioId")
                        .HasColumnType("int");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId")
                        .IsUnique();

                    b.ToTable("Valoraciones");
                });

            modelBuilder.Entity("Servientrega.Api.Models.Envio", b =>
                {
                    b.HasOne("Servientrega.Api.Models.Orden", "Orden")
                        .WithOne("Envio")
                        .HasForeignKey("Servientrega.Api.Models.Envio", "OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("Servientrega.Api.Models.Producto", b =>
                {
                    b.HasOne("Servientrega.Api.Models.Orden", null)
                        .WithMany("Productos")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Servientrega.Api.Models.Valoracion", b =>
                {
                    b.HasOne("Servientrega.Api.Models.Envio", "Envio")
                        .WithOne("Valoracion")
                        .HasForeignKey("Servientrega.Api.Models.Valoracion", "EnvioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Envio");
                });

            modelBuilder.Entity("Servientrega.Api.Models.Envio", b =>
                {
                    b.Navigation("Valoracion");
                });

            modelBuilder.Entity("Servientrega.Api.Models.Orden", b =>
                {
                    b.Navigation("Envio");

                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
